// Code generated by MockGen. DO NOT EDIT.
// Source: image_storage.go
//
// Generated by this command:
//
//	mockgen -source=image_storage.go -destination=mocks/image_storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageStorage is a mock of ImageStorage interface.
type MockImageStorage struct {
	ctrl     *gomock.Controller
	recorder *MockImageStorageMockRecorder
	isgomock struct{}
}

// MockImageStorageMockRecorder is the mock recorder for MockImageStorage.
type MockImageStorageMockRecorder struct {
	mock *MockImageStorage
}

// NewMockImageStorage creates a new mock instance.
func NewMockImageStorage(ctrl *gomock.Controller) *MockImageStorage {
	mock := &MockImageStorage{ctrl: ctrl}
	mock.recorder = &MockImageStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageStorage) EXPECT() *MockImageStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockImageStorage) Delete(url string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", url)
}

// Delete indicates an expected call of Delete.
func (mr *MockImageStorageMockRecorder) Delete(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImageStorage)(nil).Delete), url)
}

// IsStoredURL mocks base method.
func (m *MockImageStorage) IsStoredURL(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStoredURL", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsStoredURL indicates an expected call of IsStoredURL.
func (mr *MockImageStorageMockRecorder) IsStoredURL(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStoredURL", reflect.TypeOf((*MockImageStorage)(nil).IsStoredURL), url)
}

// Save mocks base method.
func (m *MockImageStorage) Save(data []byte, ext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", data, ext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockImageStorageMockRecorder) Save(data, ext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockImageStorage)(nil).Save), data, ext)
}
