// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	model "wherewhat/internal/storage/model"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CountItemsByLocation mocks base method.
func (m *MockStorage) CountItemsByLocation(ctx context.Context, locationID uint64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountItemsByLocation", ctx, locationID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountItemsByLocation indicates an expected call of CountItemsByLocation.
func (mr *MockStorageMockRecorder) CountItemsByLocation(ctx, locationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountItemsByLocation", reflect.TypeOf((*MockStorage)(nil).CountItemsByLocation), ctx, locationID)
}

// CreateItem mocks base method.
func (m *MockStorage) CreateItem(ctx context.Context, name, notes string, locationID uint64, now time.Time) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, name, notes, locationID, now)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockStorageMockRecorder) CreateItem(ctx, name, notes, locationID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockStorage)(nil).CreateItem), ctx, name, notes, locationID, now)
}

// DeleteItem mocks base method.
func (m *MockStorage) DeleteItem(ctx context.Context, id uint64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockStorageMockRecorder) DeleteItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockStorage)(nil).DeleteItem), ctx, id)
}

// FindItemByID mocks base method.
func (m *MockStorage) FindItemByID(ctx context.Context, id uint64) (model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindItemByID", ctx, id)
	ret0, _ := ret[0].(model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindItemByID indicates an expected call of FindItemByID.
func (mr *MockStorageMockRecorder) FindItemByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindItemByID", reflect.TypeOf((*MockStorage)(nil).FindItemByID), ctx, id)
}

// ItemImageURLs mocks base method.
func (m *MockStorage) ItemImageURLs(ctx context.Context, itemID uint64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemImageURLs", ctx, itemID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ItemImageURLs indicates an expected call of ItemImageURLs.
func (mr *MockStorageMockRecorder) ItemImageURLs(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemImageURLs", reflect.TypeOf((*MockStorage)(nil).ItemImageURLs), ctx, itemID)
}

// ListItemImages mocks base method.
func (m *MockStorage) ListItemImages(ctx context.Context, itemIDs []uint64) (map[uint64][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemImages", ctx, itemIDs)
	ret0, _ := ret[0].(map[uint64][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemImages indicates an expected call of ListItemImages.
func (mr *MockStorageMockRecorder) ListItemImages(ctx, itemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemImages", reflect.TypeOf((*MockStorage)(nil).ListItemImages), ctx, itemIDs)
}

// ListItems mocks base method.
func (m *MockStorage) ListItems(ctx context.Context) ([]model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx)
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockStorageMockRecorder) ListItems(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockStorage)(nil).ListItems), ctx)
}

// ReplaceItemImages mocks base method.
func (m *MockStorage) ReplaceItemImages(ctx context.Context, itemID uint64, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceItemImages", ctx, itemID, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceItemImages indicates an expected call of ReplaceItemImages.
func (mr *MockStorageMockRecorder) ReplaceItemImages(ctx, itemID, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceItemImages", reflect.TypeOf((*MockStorage)(nil).ReplaceItemImages), ctx, itemID, urls)
}

// UpdateItem mocks base method.
func (m *MockStorage) UpdateItem(ctx context.Context, id uint64, name, notes string, locationID uint64, now time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, id, name, notes, locationID, now)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockStorageMockRecorder) UpdateItem(ctx, id, name, notes, locationID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockStorage)(nil).UpdateItem), ctx, id, name, notes, locationID, now)
}
