// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/storage_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "wherewhat/internal/storage/model"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CountUsers mocks base method.
func (m *MockStorage) CountUsers(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStorageMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStorage)(nil).CountUsers), ctx)
}

// CreateUser mocks base method.
func (m *MockStorage) CreateUser(ctx context.Context, username, passwordHash string, settings model.UserSettings) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, passwordHash, settings)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageMockRecorder) CreateUser(ctx, username, passwordHash, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorage)(nil).CreateUser), ctx, username, passwordHash, settings)
}

// FindUserByID mocks base method.
func (m *MockStorage) FindUserByID(ctx context.Context, id uint64) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, id)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockStorageMockRecorder) FindUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockStorage)(nil).FindUserByID), ctx, id)
}

// FindUserByUsername mocks base method.
func (m *MockStorage) FindUserByUsername(ctx context.Context, username string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUsername", ctx, username)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUsername indicates an expected call of FindUserByUsername.
func (mr *MockStorageMockRecorder) FindUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUsername", reflect.TypeOf((*MockStorage)(nil).FindUserByUsername), ctx, username)
}

// UpdateUserLanguage mocks base method.
func (m *MockStorage) UpdateUserLanguage(ctx context.Context, id uint64, lang string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLanguage", ctx, id, lang)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLanguage indicates an expected call of UpdateUserLanguage.
func (mr *MockStorageMockRecorder) UpdateUserLanguage(ctx, id, lang any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLanguage", reflect.TypeOf((*MockStorage)(nil).UpdateUserLanguage), ctx, id, lang)
}

// UpdateUserLocationFilterDepth mocks base method.
func (m *MockStorage) UpdateUserLocationFilterDepth(ctx context.Context, id uint64, depth int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLocationFilterDepth", ctx, id, depth)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLocationFilterDepth indicates an expected call of UpdateUserLocationFilterDepth.
func (mr *MockStorageMockRecorder) UpdateUserLocationFilterDepth(ctx, id, depth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLocationFilterDepth", reflect.TypeOf((*MockStorage)(nil).UpdateUserLocationFilterDepth), ctx, id, depth)
}

// UpdateUserPasswordHash mocks base method.
func (m *MockStorage) UpdateUserPasswordHash(ctx context.Context, id uint64, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPasswordHash", ctx, id, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPasswordHash indicates an expected call of UpdateUserPasswordHash.
func (mr *MockStorageMockRecorder) UpdateUserPasswordHash(ctx, id, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPasswordHash", reflect.TypeOf((*MockStorage)(nil).UpdateUserPasswordHash), ctx, id, hash)
}

// UpdateUsername mocks base method.
func (m *MockStorage) UpdateUsername(ctx context.Context, id uint64, username string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", ctx, id, username)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername.
func (mr *MockStorageMockRecorder) UpdateUsername(ctx, id, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*MockStorage)(nil).UpdateUsername), ctx, id, username)
}
